/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Taljaard;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author 27649
 */
public class ChallengeInfoPopupScrn extends javax.swing.JFrame {

    /**
     * Creates new form BeforeScrn
     */
    public ChallengeInfoPopupScrn() {
        initComponents();
        try {
            String explanation = "";
            Scanner sc = new Scanner(new File("ChallengeInformation.txt"));
            while (sc.hasNextLine()) 
            {
                explanation = explanation + "\n" + sc.nextLine();
            }
            txtaChallengeInfo.setText(explanation);
        } catch (FileNotFoundException ex) {
            System.out.println("file not found");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlChallengeInfo = new javax.swing.JPanel();
        lblChallengeInfo = new javax.swing.JLabel();
        lblChallengeUnderstanding = new javax.swing.JLabel();
        txtaChallengeInfo = new java.awt.TextArea();
        btnContinue = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 153));

        pnlChallengeInfo.setBackground(new java.awt.Color(204, 255, 153));

        lblChallengeInfo.setText("CHALLENGE INFORMATION");
        lblChallengeInfo.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        lblChallengeInfo.setForeground(new java.awt.Color(51, 102, 0));

        lblChallengeUnderstanding.setText("Please Ensure That You Fully Understand Before Selecting Challenges");
        lblChallengeUnderstanding.setFont(new java.awt.Font("SimSun", 1, 12)); // NOI18N

        txtaChallengeInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtaChallengeInfo.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N

        btnContinue.setText("CONTINUE");
        btnContinue.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        btnContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlChallengeInfoLayout = new javax.swing.GroupLayout(pnlChallengeInfo);
        pnlChallengeInfo.setLayout(pnlChallengeInfoLayout);
        pnlChallengeInfoLayout.setHorizontalGroup(
            pnlChallengeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChallengeInfoLayout.createSequentialGroup()
                .addGroup(pnlChallengeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlChallengeInfoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblChallengeUnderstanding, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlChallengeInfoLayout.createSequentialGroup()
                        .addGroup(pnlChallengeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlChallengeInfoLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(txtaChallengeInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlChallengeInfoLayout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(lblChallengeInfo)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pnlChallengeInfoLayout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(btnContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlChallengeInfoLayout.setVerticalGroup(
            pnlChallengeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChallengeInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblChallengeInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblChallengeUnderstanding)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtaChallengeInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlChallengeInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlChallengeInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinueActionPerformed
        ChallengeSelectionScrn challenge = new ChallengeSelectionScrn();
        challenge.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnContinueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChallengeInfoPopupScrn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChallengeInfoPopupScrn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChallengeInfoPopupScrn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChallengeInfoPopupScrn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChallengeInfoPopupScrn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinue;
    private javax.swing.JLabel lblChallengeInfo;
    private javax.swing.JLabel lblChallengeUnderstanding;
    private javax.swing.JPanel pnlChallengeInfo;
    private java.awt.TextArea txtaChallengeInfo;
    // End of variables declaration//GEN-END:variables
}
