/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Taljaard;

/**
 *
 * @author 27649
 */
public class ChallengeSelectionScrn extends javax.swing.JFrame {

    /**
     * Creates new form ChallengeSelectionScrn
     */
    public ChallengeSelectionScrn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlChallengeMenu = new javax.swing.JPanel();
        lblChallengeMenu = new javax.swing.JLabel();
        lblChallengeSelection = new javax.swing.JLabel();
        lblWinderful = new java.awt.Label();
        lblSeasonALL = new java.awt.Label();
        lblDayLite = new java.awt.Label();
        lblBooMoo = new java.awt.Label();
        lblRinseDontRepeat = new java.awt.Label();
        lblAC = new java.awt.Label();
        lblWattNot = new java.awt.Label();
        lbl23Unlit = new java.awt.Label();
        radbtn2 = new javax.swing.JRadioButton();
        radbtn1 = new javax.swing.JRadioButton();
        radbtn3 = new javax.swing.JRadioButton();
        radbtn4 = new javax.swing.JRadioButton();
        radbtn6 = new javax.swing.JRadioButton();
        radbtn5 = new javax.swing.JRadioButton();
        radbtn8 = new javax.swing.JRadioButton();
        radbtn7 = new javax.swing.JRadioButton();
        lblGreenGetaway = new java.awt.Label();
        lblWaxOn = new java.awt.Label();
        lblFarmIn = new java.awt.Label();
        lblPlasticitis = new java.awt.Label();
        lbl1885 = new java.awt.Label();
        lblCupASoap = new java.awt.Label();
        lblZHero = new java.awt.Label();
        lblProFarmerJo = new java.awt.Label();
        radbtn9 = new javax.swing.JRadioButton();
        radbtn10 = new javax.swing.JRadioButton();
        radbtn11 = new javax.swing.JRadioButton();
        radbtn12 = new javax.swing.JRadioButton();
        radbtn13 = new javax.swing.JRadioButton();
        radbtn14 = new javax.swing.JRadioButton();
        radbtn15 = new javax.swing.JRadioButton();
        radbtn16 = new javax.swing.JRadioButton();
        lblChallenges = new javax.swing.JLabel();
        lblPointsAwarded = new javax.swing.JLabel();
        lblpts2 = new java.awt.Label();
        lblpts10 = new java.awt.Label();
        lblpts1 = new java.awt.Label();
        lblpts3 = new java.awt.Label();
        lblpts4 = new java.awt.Label();
        lblpts5 = new java.awt.Label();
        lblpts6 = new java.awt.Label();
        lblpts7 = new java.awt.Label();
        lblpts8 = new java.awt.Label();
        lblpts9 = new java.awt.Label();
        lblpts11 = new java.awt.Label();
        lblpts12 = new java.awt.Label();
        lblpts13 = new java.awt.Label();
        lblpts14 = new java.awt.Label();
        lblpts15 = new java.awt.Label();
        lblpts16 = new java.awt.Label();
        lblChallenges1 = new javax.swing.JLabel();
        lblPointsAwarded1 = new javax.swing.JLabel();
        btnBegin = new java.awt.Button();
        btnQry2 = new java.awt.Button();
        btnQry1 = new java.awt.Button();
        btnQry3 = new java.awt.Button();
        btnQry4 = new java.awt.Button();
        btnQry5 = new java.awt.Button();
        btnQry6 = new java.awt.Button();
        btnQry7 = new java.awt.Button();
        btnQry8 = new java.awt.Button();
        btnQry9 = new java.awt.Button();
        btnQry10 = new java.awt.Button();
        btnQry11 = new java.awt.Button();
        btnQry12 = new java.awt.Button();
        btnQry13 = new java.awt.Button();
        btnQry14 = new java.awt.Button();
        btnQry15 = new java.awt.Button();
        btnQry16 = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 153));
        setForeground(new java.awt.Color(204, 255, 153));

        pnlChallengeMenu.setBackground(new java.awt.Color(204, 255, 153));

        lblChallengeMenu.setFont(new java.awt.Font("SimSun", 1, 30)); // NOI18N
        lblChallengeMenu.setForeground(new java.awt.Color(51, 102, 0));
        lblChallengeMenu.setText("CHALLENGE MENU");

        lblChallengeSelection.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        lblChallengeSelection.setText("Please Select 10 Challenges You Would Like To Partake In");

        lblWinderful.setFont(new java.awt.Font("SimSun", 1, 16)); // NOI18N
        lblWinderful.setText("1) WINDERFUL");

        lblSeasonALL.setFont(new java.awt.Font("SimSun", 1, 16)); // NOI18N
        lblSeasonALL.setText("3) SeasonALL");

        lblDayLite.setFont(new java.awt.Font("SimSun", 1, 16)); // NOI18N
        lblDayLite.setText("6) DAY-LITE");

        lblBooMoo.setFont(new java.awt.Font("SimSun", 1, 16)); // NOI18N
        lblBooMoo.setText("2) BOO MOO");

        lblRinseDontRepeat.setFont(new java.awt.Font("SimSun", 1, 16)); // NOI18N
        lblRinseDontRepeat.setText("4) Rinse, Don't Repeat");

        lblAC.setFont(new java.awt.Font("SimSun", 1, 16)); // NOI18N
        lblAC.setName(""); // NOI18N
        lblAC.setText("7) AC: Amplified Concern");

        lblWattNot.setFont(new java.awt.Font("SimSun", 1, 16)); // NOI18N
        lblWattNot.setText("5) WATT-NOT");

        lbl23Unlit.setFont(new java.awt.Font("SimSun", 1, 16)); // NOI18N
        lbl23Unlit.setText("8) '23 UN-LIT");

        lblGreenGetaway.setFont(new java.awt.Font("SimSun", 1, 16)); // NOI18N
        lblGreenGetaway.setText("9) GREEN GETAWAY");

        lblWaxOn.setFont(new java.awt.Font("SimSun", 1, 16)); // NOI18N
        lblWaxOn.setText("16) WAX-ON");

        lblFarmIn.setFont(new java.awt.Font("SimSun", 1, 16)); // NOI18N
        lblFarmIn.setText("10) FARM-IN");

        lblPlasticitis.setFont(new java.awt.Font("SimSun", 1, 16)); // NOI18N
        lblPlasticitis.setText("11) PLASTICITIS");

        lbl1885.setFont(new java.awt.Font("SimSun", 1, 16)); // NOI18N
        lbl1885.setText("12) 1885");

        lblCupASoap.setFont(new java.awt.Font("SimSun", 1, 16)); // NOI18N
        lblCupASoap.setText("13) CUP-A-SOAP");

        lblZHero.setFont(new java.awt.Font("SimSun", 1, 16)); // NOI18N
        lblZHero.setText("14) Z-HERO");

        lblProFarmerJo.setFont(new java.awt.Font("SimSun", 1, 16)); // NOI18N
        lblProFarmerJo.setText("15) PRO-FARMER-JO");

        lblChallenges.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        lblChallenges.setText("CHALLENGES");

        lblPointsAwarded.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        lblPointsAwarded.setText("POINTS");

        lblpts2.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        lblpts2.setText("250");

        lblpts10.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        lblpts10.setText("75");

        lblpts1.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        lblpts1.setText("75");

        lblpts3.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        lblpts3.setText("50");

        lblpts4.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        lblpts4.setText("100");

        lblpts5.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        lblpts5.setText("100");

        lblpts6.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        lblpts6.setText("75");

        lblpts7.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        lblpts7.setText("50");

        lblpts8.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        lblpts8.setText("200");

        lblpts9.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        lblpts9.setText("150");

        lblpts11.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        lblpts11.setText("150");

        lblpts12.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        lblpts12.setText("150");

        lblpts13.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        lblpts13.setText("75");

        lblpts14.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        lblpts14.setText("200");

        lblpts15.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        lblpts15.setText("50");

        lblpts16.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        lblpts16.setText("150");

        lblChallenges1.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        lblChallenges1.setText("CHALLENGES");

        lblPointsAwarded1.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        lblPointsAwarded1.setText("POINTS");

        btnBegin.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        btnBegin.setLabel("BEGIN!");
        btnBegin.setName(""); // NOI18N

        btnQry2.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        btnQry2.setLabel("?");

        btnQry1.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        btnQry1.setLabel("?");

        btnQry3.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        btnQry3.setLabel("?");

        btnQry4.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        btnQry4.setLabel("?");

        btnQry5.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        btnQry5.setLabel("?");

        btnQry6.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        btnQry6.setLabel("?");

        btnQry7.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        btnQry7.setLabel("?");

        btnQry8.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        btnQry8.setLabel("?");

        btnQry9.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        btnQry9.setLabel("?");

        btnQry10.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        btnQry10.setLabel("?");

        btnQry11.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        btnQry11.setLabel("?");

        btnQry12.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        btnQry12.setLabel("?");

        btnQry13.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        btnQry13.setLabel("?");

        btnQry14.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        btnQry14.setLabel("?");

        btnQry15.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        btnQry15.setLabel("?");

        btnQry16.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        btnQry16.setLabel("?");

        javax.swing.GroupLayout pnlChallengeMenuLayout = new javax.swing.GroupLayout(pnlChallengeMenu);
        pnlChallengeMenu.setLayout(pnlChallengeMenuLayout);
        pnlChallengeMenuLayout.setHorizontalGroup(
            pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChallengeMenuLayout.createSequentialGroup()
                .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlChallengeMenuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblChallengeSelection))
                    .addGroup(pnlChallengeMenuLayout.createSequentialGroup()
                        .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlChallengeMenuLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPointsAwarded)
                                .addGap(130, 130, 130))
                            .addGroup(pnlChallengeMenuLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnlChallengeMenuLayout.createSequentialGroup()
                                            .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblWattNot, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblAC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lbl23Unlit, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(lblSeasonALL, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblRinseDontRepeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlChallengeMenuLayout.createSequentialGroup()
                                            .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(pnlChallengeMenuLayout.createSequentialGroup()
                                                    .addComponent(lblDayLite, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(lblpts6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(pnlChallengeMenuLayout.createSequentialGroup()
                                                    .addComponent(lblWinderful, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(73, 73, 73)
                                                    .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(lblpts2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblpts1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblpts3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblpts4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblpts5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblpts7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblpts8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGap(32, 32, 32)))
                                    .addGroup(pnlChallengeMenuLayout.createSequentialGroup()
                                        .addComponent(lblBooMoo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(22, 22, 22)))
                                .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(radbtn2)
                                    .addComponent(radbtn1)
                                    .addComponent(radbtn3)
                                    .addComponent(radbtn4)
                                    .addComponent(radbtn5)
                                    .addComponent(radbtn6)
                                    .addComponent(radbtn7)
                                    .addComponent(radbtn8))
                                .addGap(19, 19, 19)
                                .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnQry2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnQry1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnQry3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnQry4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnQry5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnQry6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnQry7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnQry8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)))
                        .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGreenGetaway, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblChallenges)
                            .addComponent(lblFarmIn, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPlasticitis, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl1885, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCupASoap, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblZHero, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProFarmerJo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblWaxOn, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlChallengeMenuLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblpts11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblpts12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblpts13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblpts14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblpts15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblpts16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblpts10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblpts9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlChallengeMenuLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radbtn9)
                                    .addComponent(radbtn11)
                                    .addComponent(radbtn10)
                                    .addComponent(radbtn12)
                                    .addComponent(radbtn13)
                                    .addComponent(radbtn14)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlChallengeMenuLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radbtn16, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(radbtn15, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnQry10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnQry11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnQry12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnQry13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnQry14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnQry15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnQry16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnQry9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlChallengeMenuLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPointsAwarded1)
                        .addGap(33, 33, 33)))
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlChallengeMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlChallengeMenuLayout.createSequentialGroup()
                        .addComponent(btnBegin, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(356, 356, 356))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlChallengeMenuLayout.createSequentialGroup()
                        .addComponent(lblChallengeMenu)
                        .addGap(305, 305, 305))))
            .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlChallengeMenuLayout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(lblChallenges1)
                    .addContainerGap(700, Short.MAX_VALUE)))
        );

        pnlChallengeMenuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblpts1, lblpts10, lblpts11, lblpts12, lblpts13, lblpts14, lblpts15, lblpts16, lblpts2, lblpts3, lblpts4, lblpts5, lblpts6, lblpts7, lblpts8, lblpts9});

        pnlChallengeMenuLayout.setVerticalGroup(
            pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChallengeMenuLayout.createSequentialGroup()
                .addComponent(lblChallengeMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblChallengeSelection)
                .addGap(35, 35, 35)
                .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblWinderful, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlChallengeMenuLayout.createSequentialGroup()
                        .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblChallenges)
                            .addComponent(lblPointsAwarded)
                            .addComponent(lblPointsAwarded1))
                        .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlChallengeMenuLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblpts1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(radbtn1)
                                    .addComponent(btnQry1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlChallengeMenuLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblGreenGetaway, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlChallengeMenuLayout.createSequentialGroup()
                                        .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblpts9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(radbtn9))
                                        .addGap(5, 5, 5))
                                    .addGroup(pnlChallengeMenuLayout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(btnQry9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlChallengeMenuLayout.createSequentialGroup()
                        .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblBooMoo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(radbtn2, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(lblpts2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblpts10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radbtn10)
                            .addComponent(btnQry10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radbtn11)
                            .addComponent(lblSeasonALL, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radbtn3)
                            .addComponent(lblpts3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblpts11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnQry11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlChallengeMenuLayout.createSequentialGroup()
                        .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFarmIn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnQry2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlChallengeMenuLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPlasticitis, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlChallengeMenuLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnQry3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlChallengeMenuLayout.createSequentialGroup()
                        .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRinseDontRepeat, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblpts4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblWattNot, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblpts5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlChallengeMenuLayout.createSequentialGroup()
                        .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlChallengeMenuLayout.createSequentialGroup()
                                    .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(radbtn4)
                                        .addComponent(lblpts12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(radbtn12))
                                    .addGap(15, 15, 15))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlChallengeMenuLayout.createSequentialGroup()
                                    .addComponent(lbl1885, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(pnlChallengeMenuLayout.createSequentialGroup()
                                .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnQry4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnQry12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)))
                        .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnQry5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblCupASoap, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(radbtn5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblpts13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(radbtn13, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(btnQry13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlChallengeMenuLayout.createSequentialGroup()
                        .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDayLite, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblpts6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAC, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblpts7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl23Unlit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblpts8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 80, Short.MAX_VALUE))
                    .addGroup(pnlChallengeMenuLayout.createSequentialGroup()
                        .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlChallengeMenuLayout.createSequentialGroup()
                                .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlChallengeMenuLayout.createSequentialGroup()
                                        .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblpts14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblZHero, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblProFarmerJo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblpts15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlChallengeMenuLayout.createSequentialGroup()
                                        .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(radbtn14)
                                            .addComponent(btnQry14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnQry15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(radbtn15))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnlChallengeMenuLayout.createSequentialGroup()
                                .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(radbtn7)
                                    .addComponent(btnQry6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnQry7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlChallengeMenuLayout.createSequentialGroup()
                                        .addComponent(radbtn6)
                                        .addGap(7, 7, 7)))
                                .addGap(5, 5, 5)))
                        .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(pnlChallengeMenuLayout.createSequentialGroup()
                                    .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblpts16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(radbtn16))
                                    .addGap(4, 4, 4))
                                .addComponent(lblWaxOn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlChallengeMenuLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnQry8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(radbtn8)))
                            .addComponent(btnQry16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBegin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
            .addGroup(pnlChallengeMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlChallengeMenuLayout.createSequentialGroup()
                    .addGap(97, 97, 97)
                    .addComponent(lblChallenges1)
                    .addContainerGap(414, Short.MAX_VALUE)))
        );

        pnlChallengeMenuLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblpts1, lblpts10, lblpts11, lblpts12, lblpts13, lblpts14, lblpts15, lblpts16, lblpts2, lblpts3, lblpts4, lblpts5, lblpts6, lblpts7, lblpts8, lblpts9});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlChallengeMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlChallengeMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChallengeSelectionScrn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChallengeSelectionScrn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChallengeSelectionScrn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChallengeSelectionScrn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChallengeSelectionScrn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnBegin;
    private java.awt.Button btnQry1;
    private java.awt.Button btnQry10;
    private java.awt.Button btnQry11;
    private java.awt.Button btnQry12;
    private java.awt.Button btnQry13;
    private java.awt.Button btnQry14;
    private java.awt.Button btnQry15;
    private java.awt.Button btnQry16;
    private java.awt.Button btnQry2;
    private java.awt.Button btnQry3;
    private java.awt.Button btnQry4;
    private java.awt.Button btnQry5;
    private java.awt.Button btnQry6;
    private java.awt.Button btnQry7;
    private java.awt.Button btnQry8;
    private java.awt.Button btnQry9;
    private java.awt.Label lbl1885;
    private java.awt.Label lbl23Unlit;
    private java.awt.Label lblAC;
    private java.awt.Label lblBooMoo;
    private javax.swing.JLabel lblChallengeMenu;
    private javax.swing.JLabel lblChallengeSelection;
    private javax.swing.JLabel lblChallenges;
    private javax.swing.JLabel lblChallenges1;
    private java.awt.Label lblCupASoap;
    private java.awt.Label lblDayLite;
    private java.awt.Label lblFarmIn;
    private java.awt.Label lblGreenGetaway;
    private java.awt.Label lblPlasticitis;
    private javax.swing.JLabel lblPointsAwarded;
    private javax.swing.JLabel lblPointsAwarded1;
    private java.awt.Label lblProFarmerJo;
    private java.awt.Label lblRinseDontRepeat;
    private java.awt.Label lblSeasonALL;
    private java.awt.Label lblWattNot;
    private java.awt.Label lblWaxOn;
    private java.awt.Label lblWinderful;
    private java.awt.Label lblZHero;
    private java.awt.Label lblpts1;
    private java.awt.Label lblpts10;
    private java.awt.Label lblpts11;
    private java.awt.Label lblpts12;
    private java.awt.Label lblpts13;
    private java.awt.Label lblpts14;
    private java.awt.Label lblpts15;
    private java.awt.Label lblpts16;
    private java.awt.Label lblpts2;
    private java.awt.Label lblpts3;
    private java.awt.Label lblpts4;
    private java.awt.Label lblpts5;
    private java.awt.Label lblpts6;
    private java.awt.Label lblpts7;
    private java.awt.Label lblpts8;
    private java.awt.Label lblpts9;
    private javax.swing.JPanel pnlChallengeMenu;
    private javax.swing.JRadioButton radbtn1;
    private javax.swing.JRadioButton radbtn10;
    private javax.swing.JRadioButton radbtn11;
    private javax.swing.JRadioButton radbtn12;
    private javax.swing.JRadioButton radbtn13;
    private javax.swing.JRadioButton radbtn14;
    private javax.swing.JRadioButton radbtn15;
    private javax.swing.JRadioButton radbtn16;
    private javax.swing.JRadioButton radbtn2;
    private javax.swing.JRadioButton radbtn3;
    private javax.swing.JRadioButton radbtn4;
    private javax.swing.JRadioButton radbtn5;
    private javax.swing.JRadioButton radbtn6;
    private javax.swing.JRadioButton radbtn7;
    private javax.swing.JRadioButton radbtn8;
    private javax.swing.JRadioButton radbtn9;
    // End of variables declaration//GEN-END:variables
}
