/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Taljaard;

/**
 *
 * @author 27649
 */
public class CongratulationsScrn extends javax.swing.JFrame {

    /**
     * Creates new form CongratulationsScrn
     */
    public CongratulationsScrn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCongrats = new java.awt.Panel();
        lblCongratulations = new javax.swing.JLabel();
        lblOfficialCompleted = new java.awt.Label();
        lblThankYou = new java.awt.Label();
        btnSeeFinalResults = new javax.swing.JButton();
        prbar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlCongrats.setBackground(new java.awt.Color(204, 255, 153));

        lblCongratulations.setFont(new java.awt.Font("SimSun", 1, 28)); // NOI18N
        lblCongratulations.setForeground(new java.awt.Color(51, 102, 0));
        lblCongratulations.setText("CONGRATULATIONS!");

        lblOfficialCompleted.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        lblOfficialCompleted.setText("You Have Officially Completed the Little Foot Competition!");

        lblThankYou.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        lblThankYou.setText("THANK YOU FOR MAKING A DIFFERENCE!");

        btnSeeFinalResults.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        btnSeeFinalResults.setText("SEE FINAL RESULTS");

        javax.swing.GroupLayout pnlCongratsLayout = new javax.swing.GroupLayout(pnlCongrats);
        pnlCongrats.setLayout(pnlCongratsLayout);
        pnlCongratsLayout.setHorizontalGroup(
            pnlCongratsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCongratsLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(pnlCongratsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCongratsLayout.createSequentialGroup()
                        .addComponent(btnSeeFinalResults, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCongratsLayout.createSequentialGroup()
                        .addComponent(lblThankYou, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCongratsLayout.createSequentialGroup()
                        .addComponent(lblOfficialCompleted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(pnlCongratsLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(pnlCongratsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prbar, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCongratulations))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlCongratsLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnSeeFinalResults, lblCongratulations, prbar});

        pnlCongratsLayout.setVerticalGroup(
            pnlCongratsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCongratsLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(lblCongratulations, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(prbar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(lblOfficialCompleted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblThankYou, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnSeeFinalResults)
                .addGap(30, 30, 30))
        );

        pnlCongratsLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnSeeFinalResults, lblCongratulations, prbar});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCongrats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlCongrats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CongratulationsScrn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CongratulationsScrn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CongratulationsScrn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CongratulationsScrn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CongratulationsScrn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSeeFinalResults;
    private javax.swing.JLabel lblCongratulations;
    private java.awt.Label lblOfficialCompleted;
    private java.awt.Label lblThankYou;
    private java.awt.Panel pnlCongrats;
    private javax.swing.JProgressBar prbar;
    // End of variables declaration//GEN-END:variables
}
