/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Taljaard;

/**
 *
 * @author 27649
 */
public class FinalResultsScrn extends javax.swing.JFrame {

    /**
     * Creates new form FinalResultsScrn
     */
    public FinalResultsScrn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlResults = new javax.swing.JPanel();
        lblFinalResult = new javax.swing.JLabel();
        lblRanking = new javax.swing.JLabel();
        lblTotalPoints = new javax.swing.JLabel();
        lblPercentile = new javax.swing.JLabel();
        lstLeaderboard = new java.awt.List();
        lblLeaderboard = new javax.swing.JLabel();
        txtfPercentile = new javax.swing.JTextField();
        txtfPoints = new javax.swing.JTextField();
        txtfRanking = new javax.swing.JTextField();
        lblContinue = new java.awt.Label();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlResults.setBackground(new java.awt.Color(204, 255, 153));

        lblFinalResult.setFont(new java.awt.Font("SimSun", 1, 28)); // NOI18N
        lblFinalResult.setForeground(new java.awt.Color(51, 102, 0));
        lblFinalResult.setText("FINAL RESULTS");

        lblRanking.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        lblRanking.setText("FINAL RANKING");

        lblTotalPoints.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        lblTotalPoints.setText("TOTAL POINTS");

        lblPercentile.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        lblPercentile.setText("PERCENTILE");

        lstLeaderboard.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        lstLeaderboard.setMultipleMode(true);

        lblLeaderboard.setFont(new java.awt.Font("SimSun", 1, 28)); // NOI18N
        lblLeaderboard.setForeground(new java.awt.Color(51, 102, 0));
        lblLeaderboard.setText("LEADERBOARD");

        txtfPercentile.setEditable(false);
        txtfPercentile.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N

        txtfPoints.setEditable(false);
        txtfPoints.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N

        txtfRanking.setEditable(false);
        txtfRanking.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N

        lblContinue.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        lblContinue.setText("CONTINUE TO MAKE A DIFFERENCE!");

        btnExit.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        btnExit.setText("EXIT");

        javax.swing.GroupLayout pnlResultsLayout = new javax.swing.GroupLayout(pnlResults);
        pnlResults.setLayout(pnlResultsLayout);
        pnlResultsLayout.setHorizontalGroup(
            pnlResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlResultsLayout.createSequentialGroup()
                .addGroup(pnlResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlResultsLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(pnlResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlResultsLayout.createSequentialGroup()
                                .addComponent(lblTotalPoints)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtfPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlResultsLayout.createSequentialGroup()
                                .addComponent(lblPercentile)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtfPercentile, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlResultsLayout.createSequentialGroup()
                                .addComponent(lblRanking)
                                .addGap(60, 60, 60)
                                .addComponent(txtfRanking, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlResultsLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(lblFinalResult)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(61, 61, 61))
            .addGroup(pnlResultsLayout.createSequentialGroup()
                .addGroup(pnlResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlResultsLayout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlResultsLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(lblLeaderboard))
                    .addGroup(pnlResultsLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(lstLeaderboard, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlResultsLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(lblContinue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlResultsLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblPercentile, lblRanking, lblTotalPoints, txtfPercentile, txtfPoints, txtfRanking});

        pnlResultsLayout.setVerticalGroup(
            pnlResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFinalResult, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRanking, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfRanking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(pnlResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPercentile, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfPercentile, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotalPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(lblLeaderboard, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lstLeaderboard, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(lblContinue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(btnExit)
                .addGap(26, 26, 26))
        );

        pnlResultsLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblPercentile, lblRanking, lblTotalPoints, txtfPercentile, txtfPoints, txtfRanking});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlResults, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlResults, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinalResultsScrn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinalResultsScrn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinalResultsScrn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinalResultsScrn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinalResultsScrn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private java.awt.Label lblContinue;
    private javax.swing.JLabel lblFinalResult;
    private javax.swing.JLabel lblLeaderboard;
    private javax.swing.JLabel lblPercentile;
    private javax.swing.JLabel lblRanking;
    private javax.swing.JLabel lblTotalPoints;
    private java.awt.List lstLeaderboard;
    private javax.swing.JPanel pnlResults;
    private javax.swing.JTextField txtfPercentile;
    private javax.swing.JTextField txtfPoints;
    private javax.swing.JTextField txtfRanking;
    // End of variables declaration//GEN-END:variables
}
