/*                     
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Taljaard;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

/**
 *
 * @author 27649
 */
public class MainMenuScrn extends javax.swing.JFrame {

    
    
    
    /**
     * Creates new form MainMenuScrn
     */
    public MainMenuScrn() {
        initComponents();
        //splitting written data from text file, changing the text in the background tab
        String arrB[] = Access.accessBackground().split("#");
        txtaAbout.setText(arrB[0]);
        txtaDifference.setText(arrB[1]);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabpnMenu = new javax.swing.JTabbedPane();
        pnlProfile = new javax.swing.JPanel();
        lblSelectedChallenges = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblUserProfile = new javax.swing.JLabel();
        lblHouseHoldMembers = new javax.swing.JLabel();
        txtHouseholdMembers = new java.awt.TextField();
        txtUserName = new java.awt.TextField();
        lstSelectedChallenges = new java.awt.List();
        prbar = new javax.swing.JProgressBar();
        pnlProgress = new javax.swing.JPanel();
        prbar1 = new javax.swing.JProgressBar();
        lblDaysLeft = new javax.swing.JLabel();
        lblProgress = new javax.swing.JLabel();
        lblProgressHeading = new javax.swing.JLabel();
        txtCurrentRanking = new java.awt.TextField();
        lblNiceWorkSoFar = new javax.swing.JLabel();
        txtDaysLeft = new java.awt.TextField();
        lblCurrentRanking = new javax.swing.JLabel();
        lblPointsEarned = new javax.swing.JLabel();
        txtPointsEarned = new java.awt.TextField();
        pnlDailyChecklist = new javax.swing.JPanel();
        lblDailyChecklist = new javax.swing.JLabel();
        lblChecklistDisclaimer = new javax.swing.JLabel();
        lblChecklistSelection = new javax.swing.JLabel();
        lblChallenge1 = new javax.swing.JLabel();
        lblChallenge2 = new javax.swing.JLabel();
        lblChallenge3 = new javax.swing.JLabel();
        lblChallenge4 = new javax.swing.JLabel();
        lblChallenge5 = new javax.swing.JLabel();
        lblChallenge6 = new javax.swing.JLabel();
        lblChallenge7 = new javax.swing.JLabel();
        lblChallenge8 = new javax.swing.JLabel();
        lblChallenge9 = new javax.swing.JLabel();
        lblChallenge10 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        btnSubmitChecklist = new java.awt.Button();
        lblDay = new javax.swing.JLabel();
        txtfDay = new javax.swing.JTextField();
        pnlBonusChallenge = new javax.swing.JPanel();
        lblBonusChallenge = new javax.swing.JLabel();
        lblBonusDisclaimer = new javax.swing.JLabel();
        scrlpExplanation = new javax.swing.JScrollPane();
        txtaChallengeExplanation = new javax.swing.JTextArea();
        lblBonusCompleted = new javax.swing.JLabel();
        txtfPointsAwarded = new javax.swing.JTextField();
        txtfBonusName = new javax.swing.JTextField();
        btnSubmitBonus = new java.awt.Button();
        rdbtnYesBonus = new javax.swing.JRadioButton();
        lblPointsAwarded = new javax.swing.JLabel();
        pnlBackground = new javax.swing.JPanel();
        lblBackground = new javax.swing.JLabel();
        lblAboutLittleFoot = new javax.swing.JLabel();
        lblHowYoureHelping = new javax.swing.JLabel();
        sclpnAbout = new javax.swing.JScrollPane();
        txtaAbout = new javax.swing.JTextArea();
        scrlpnDifference = new javax.swing.JScrollPane();
        txtaDifference = new javax.swing.JTextArea();
        lblThankYou = new javax.swing.JLabel();
        pnlHelp = new javax.swing.JPanel();
        lblHelp = new javax.swing.JLabel();
        lblHelpExplanation = new javax.swing.JLabel();
        btnChallenges = new javax.swing.JButton();
        scrlpnHelp = new javax.swing.JScrollPane();
        txtaQueries = new javax.swing.JTextArea();
        btnUserPass = new javax.swing.JButton();
        btnTimeLeft = new javax.swing.JButton();
        btnPointSystem = new javax.swing.JButton();
        btnDeclaration = new javax.swing.JButton();
        btnBonusChallenge = new javax.swing.JButton();
        btnDailyChecklist = new javax.swing.JButton();
        btnChallengeTips = new javax.swing.JButton();
        tabpnChallengeTips = new javax.swing.JTabbedPane();
        pnl1 = new javax.swing.JPanel();
        lblTip1 = new javax.swing.JLabel();
        scrpnTip1 = new javax.swing.JScrollPane();
        txtaTip1 = new javax.swing.JTextArea();
        btnTip1 = new javax.swing.JButton();
        pnl2 = new javax.swing.JPanel();
        lblTip2 = new javax.swing.JLabel();
        scrpnTip2 = new javax.swing.JScrollPane();
        txtaTip2 = new javax.swing.JTextArea();
        btnTip2 = new javax.swing.JButton();
        pnl3 = new javax.swing.JPanel();
        lblTip3 = new javax.swing.JLabel();
        btnTip3 = new javax.swing.JButton();
        scrpnTip7 = new javax.swing.JScrollPane();
        txtaTip3 = new javax.swing.JTextArea();
        pnl4 = new javax.swing.JPanel();
        lblTip4 = new javax.swing.JLabel();
        scrpnTip4 = new javax.swing.JScrollPane();
        txtaTip4 = new javax.swing.JTextArea();
        btnTip4 = new javax.swing.JButton();
        pnl5 = new javax.swing.JPanel();
        lblTip5 = new javax.swing.JLabel();
        scrpnTip5 = new javax.swing.JScrollPane();
        txtaTip5 = new javax.swing.JTextArea();
        btnTip5 = new javax.swing.JButton();
        pnl6 = new javax.swing.JPanel();
        lblTip6 = new javax.swing.JLabel();
        btnTip6 = new javax.swing.JButton();
        scrpnTip11 = new javax.swing.JScrollPane();
        txtaTip6 = new javax.swing.JTextArea();
        pnl7 = new javax.swing.JPanel();
        lblTip7 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtaTip7 = new javax.swing.JTextArea();
        btnTip7 = new javax.swing.JButton();
        pnl8 = new javax.swing.JPanel();
        lblTip8 = new javax.swing.JLabel();
        scrpnTip8 = new javax.swing.JScrollPane();
        txtaTip8 = new javax.swing.JTextArea();
        btnTip8 = new javax.swing.JButton();
        pnl9 = new javax.swing.JPanel();
        lblTip9 = new javax.swing.JLabel();
        btnTip9 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtaTip9 = new javax.swing.JTextArea();
        pnl10 = new javax.swing.JPanel();
        lblTip10 = new javax.swing.JLabel();
        scrpnTip10 = new javax.swing.JScrollPane();
        txtaTip10 = new javax.swing.JTextArea();
        btnTip10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabpnMenu.setBackground(new java.awt.Color(204, 255, 204));
        tabpnMenu.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        tabpnMenu.setFont(new java.awt.Font("SimSun", 1, 16)); // NOI18N

        pnlProfile.setBackground(new java.awt.Color(204, 255, 153));

        lblSelectedChallenges.setFont(new java.awt.Font("SimSun", 1, 16)); // NOI18N
        lblSelectedChallenges.setText("SELECTED CHALLENGES");

        lblUserName.setFont(new java.awt.Font("SimSun", 1, 16)); // NOI18N
        lblUserName.setText("USERNAME");

        lblUserProfile.setFont(new java.awt.Font("SimSun", 1, 20)); // NOI18N
        lblUserProfile.setForeground(new java.awt.Color(51, 102, 0));
        lblUserProfile.setText("USER PROFILE");

        lblHouseHoldMembers.setFont(new java.awt.Font("SimSun", 1, 16)); // NOI18N
        lblHouseHoldMembers.setText("HOUSEHOLD MEMBERS");

        txtHouseholdMembers.setEditable(false);
        txtHouseholdMembers.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N

        txtUserName.setEditable(false);
        txtUserName.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N

        javax.swing.GroupLayout pnlProfileLayout = new javax.swing.GroupLayout(pnlProfile);
        pnlProfile.setLayout(pnlProfileLayout);
        pnlProfileLayout.setHorizontalGroup(
            pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProfileLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(prbar, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
            .addGroup(pnlProfileLayout.createSequentialGroup()
                .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProfileLayout.createSequentialGroup()
                        .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlProfileLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProfileLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHouseHoldMembers)
                                    .addComponent(lblSelectedChallenges))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtHouseholdMembers, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lstSelectedChallenges, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlProfileLayout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(lblUserProfile)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlProfileLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lstSelectedChallenges, txtHouseholdMembers, txtUserName});

        pnlProfileLayout.setVerticalGroup(
            pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProfileLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblUserProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtHouseholdMembers, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHouseHoldMembers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lstSelectedChallenges, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSelectedChallenges, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(prbar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );

        pnlProfileLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblHouseHoldMembers, txtHouseholdMembers});

        tabpnMenu.addTab("USER PROFILE", pnlProfile);

        pnlProgress.setBackground(new java.awt.Color(204, 255, 153));

        lblDaysLeft.setFont(new java.awt.Font("SimSun", 1, 16)); // NOI18N
        lblDaysLeft.setText("DAYS LEFT");

        lblProgress.setFont(new java.awt.Font("SimSun", 1, 16)); // NOI18N
        lblProgress.setText("PROGRESS");

        lblProgressHeading.setFont(new java.awt.Font("SimSun", 1, 20)); // NOI18N
        lblProgressHeading.setForeground(new java.awt.Color(51, 102, 0));
        lblProgressHeading.setText("PROGRESS");

        txtCurrentRanking.setEditable(false);
        txtCurrentRanking.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N

        lblNiceWorkSoFar.setFont(new java.awt.Font("SimSun", 1, 20)); // NOI18N
        lblNiceWorkSoFar.setForeground(new java.awt.Color(51, 102, 0));
        lblNiceWorkSoFar.setText("NICE WORK SO FAR!");

        txtDaysLeft.setEditable(false);
        txtDaysLeft.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N

        lblCurrentRanking.setFont(new java.awt.Font("SimSun", 1, 16)); // NOI18N
        lblCurrentRanking.setText("CURRENT RANKING");

        lblPointsEarned.setFont(new java.awt.Font("SimSun", 1, 16)); // NOI18N
        lblPointsEarned.setText("POINTS EARNED");

        txtPointsEarned.setEditable(false);
        txtPointsEarned.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N

        javax.swing.GroupLayout pnlProgressLayout = new javax.swing.GroupLayout(pnlProgress);
        pnlProgress.setLayout(pnlProgressLayout);
        pnlProgressLayout.setHorizontalGroup(
            pnlProgressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProgressLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pnlProgressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDaysLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPointsEarned, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCurrentRanking, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(pnlProgressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtCurrentRanking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDaysLeft, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prbar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                    .addComponent(txtPointsEarned, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE))
                .addGap(24, 24, 24))
            .addGroup(pnlProgressLayout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(lblProgressHeading)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlProgressLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(lblNiceWorkSoFar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlProgressLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {prbar1, txtCurrentRanking, txtDaysLeft, txtPointsEarned});

        pnlProgressLayout.setVerticalGroup(
            pnlProgressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProgressLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblProgressHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(pnlProgressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlProgressLayout.createSequentialGroup()
                        .addGroup(pnlProgressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prbar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProgress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addComponent(txtDaysLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblDaysLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(pnlProgressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPointsEarned, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPointsEarned, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnlProgressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCurrentRanking, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCurrentRanking, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(lblNiceWorkSoFar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        pnlProgressLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblCurrentRanking, lblDaysLeft, lblPointsEarned, lblProgress, prbar1, txtCurrentRanking, txtDaysLeft, txtPointsEarned});

        tabpnMenu.addTab("PROGRESS", pnlProgress);

        pnlDailyChecklist.setBackground(new java.awt.Color(204, 255, 153));

        lblDailyChecklist.setFont(new java.awt.Font("SimSun", 1, 20)); // NOI18N
        lblDailyChecklist.setForeground(new java.awt.Color(51, 102, 0));
        lblDailyChecklist.setText("DAILY CHECKLIST");

        lblChecklistDisclaimer.setFont(new java.awt.Font("SimSun", 1, 12)); // NOI18N
        lblChecklistDisclaimer.setText("Please Complete This Daily To Achieve All the Points You've Earned");

        lblChecklistSelection.setFont(new java.awt.Font("SimSun", 1, 12)); // NOI18N
        lblChecklistSelection.setText("Only Select the Challenges That You Successfully Completed Today");

        lblChallenge1.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        lblChallenge1.setText("1)");

        lblChallenge2.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        lblChallenge2.setText("2)");

        lblChallenge3.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        lblChallenge3.setText("3)");

        lblChallenge4.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        lblChallenge4.setText("4)");

        lblChallenge5.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        lblChallenge5.setText("5)");

        lblChallenge6.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        lblChallenge6.setText("6)");

        lblChallenge7.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        lblChallenge7.setText("7)");

        lblChallenge8.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        lblChallenge8.setText("8)");

        lblChallenge9.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        lblChallenge9.setText("9)");

        lblChallenge10.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        lblChallenge10.setText("10)");

        btnSubmitChecklist.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        btnSubmitChecklist.setLabel("SUBMIT");
        btnSubmitChecklist.setName(""); // NOI18N

        lblDay.setFont(new java.awt.Font("SimSun", 1, 20)); // NOI18N
        lblDay.setForeground(new java.awt.Color(51, 102, 0));
        lblDay.setText("DAY:");

        txtfDay.setEditable(false);
        txtfDay.setFont(new java.awt.Font("SimSun", 1, 20)); // NOI18N

        javax.swing.GroupLayout pnlDailyChecklistLayout = new javax.swing.GroupLayout(pnlDailyChecklist);
        pnlDailyChecklist.setLayout(pnlDailyChecklistLayout);
        pnlDailyChecklistLayout.setHorizontalGroup(
            pnlDailyChecklistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDailyChecklistLayout.createSequentialGroup()
                .addGap(0, 59, Short.MAX_VALUE)
                .addGroup(pnlDailyChecklistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblChecklistDisclaimer)
                    .addGroup(pnlDailyChecklistLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(pnlDailyChecklistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblChecklistSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlDailyChecklistLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(pnlDailyChecklistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblChallenge1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlDailyChecklistLayout.createSequentialGroup()
                                        .addGroup(pnlDailyChecklistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(lblChallenge9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblChallenge8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblChallenge7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblChallenge6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblChallenge5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblChallenge4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblChallenge3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblChallenge2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblChallenge10, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
                                        .addGap(65, 65, 65)
                                        .addGroup(pnlDailyChecklistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jRadioButton2)
                                            .addComponent(jRadioButton3)
                                            .addComponent(jRadioButton4)
                                            .addComponent(jRadioButton1)
                                            .addComponent(jRadioButton5)
                                            .addComponent(jRadioButton6)
                                            .addComponent(jRadioButton7)
                                            .addComponent(jRadioButton8)
                                            .addComponent(jRadioButton9)
                                            .addComponent(jRadioButton10))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnSubmitChecklist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(pnlDailyChecklistLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblDay, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtfDay, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lblDailyChecklist)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlDailyChecklistLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblDay, txtfDay});

        pnlDailyChecklistLayout.setVerticalGroup(
            pnlDailyChecklistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDailyChecklistLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDailyChecklistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDay, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDailyChecklist, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblChecklistDisclaimer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblChecklistSelection)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDailyChecklistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDailyChecklistLayout.createSequentialGroup()
                        .addComponent(lblChallenge1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(lblChallenge2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(lblChallenge3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDailyChecklistLayout.createSequentialGroup()
                        .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addGroup(pnlDailyChecklistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblChallenge4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDailyChecklistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDailyChecklistLayout.createSequentialGroup()
                        .addComponent(lblChallenge5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblChallenge6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblChallenge7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDailyChecklistLayout.createSequentialGroup()
                        .addComponent(jRadioButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jRadioButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jRadioButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDailyChecklistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblChallenge8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDailyChecklistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblChallenge9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlDailyChecklistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDailyChecklistLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDailyChecklistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblChallenge10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDailyChecklistLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSubmitChecklist, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))))
        );

        pnlDailyChecklistLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblDailyChecklist, lblDay, txtfDay});

        tabpnMenu.addTab("DAILY CHECKLIST", pnlDailyChecklist);

        pnlBonusChallenge.setBackground(new java.awt.Color(204, 255, 153));

        lblBonusChallenge.setFont(new java.awt.Font("SimSun", 1, 20)); // NOI18N
        lblBonusChallenge.setForeground(new java.awt.Color(51, 102, 0));
        lblBonusChallenge.setText("DAILY BONUS CHALLENGE");

        lblBonusDisclaimer.setFont(new java.awt.Font("SimSun", 1, 12)); // NOI18N
        lblBonusDisclaimer.setText("This Challenge is Optional... Please Only State 'Yes' If Truly Completed");

        txtaChallengeExplanation.setEditable(false);
        txtaChallengeExplanation.setColumns(20);
        txtaChallengeExplanation.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        txtaChallengeExplanation.setLineWrap(true);
        txtaChallengeExplanation.setRows(5);
        txtaChallengeExplanation.setText("EXPLANATION:");
        scrlpExplanation.setViewportView(txtaChallengeExplanation);

        lblBonusCompleted.setFont(new java.awt.Font("SimSun", 1, 16)); // NOI18N
        lblBonusCompleted.setText("COMPLETED?");

        txtfPointsAwarded.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N

        txtfBonusName.setFont(new java.awt.Font("SimSun", 3, 14)); // NOI18N

        btnSubmitBonus.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        btnSubmitBonus.setLabel("SUBMIT");
        btnSubmitBonus.setName(""); // NOI18N

        rdbtnYesBonus.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        rdbtnYesBonus.setText("YES");

        lblPointsAwarded.setFont(new java.awt.Font("SimSun", 1, 16)); // NOI18N
        lblPointsAwarded.setText("POINTS AWARDED");

        javax.swing.GroupLayout pnlBonusChallengeLayout = new javax.swing.GroupLayout(pnlBonusChallenge);
        pnlBonusChallenge.setLayout(pnlBonusChallengeLayout);
        pnlBonusChallengeLayout.setHorizontalGroup(
            pnlBonusChallengeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBonusChallengeLayout.createSequentialGroup()
                .addGroup(pnlBonusChallengeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBonusChallengeLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(pnlBonusChallengeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblBonusCompleted, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPointsAwarded, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlBonusChallengeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfPointsAwarded, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdbtnYesBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlBonusChallengeLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblBonusDisclaimer)))
                .addGap(0, 44, Short.MAX_VALUE))
            .addGroup(pnlBonusChallengeLayout.createSequentialGroup()
                .addGroup(pnlBonusChallengeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBonusChallengeLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(pnlBonusChallengeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(scrlpExplanation, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                            .addComponent(txtfBonusName)))
                    .addGroup(pnlBonusChallengeLayout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(btnSubmitBonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlBonusChallengeLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(lblBonusChallenge)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlBonusChallengeLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblBonusCompleted, lblPointsAwarded});

        pnlBonusChallengeLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {scrlpExplanation, txtfBonusName});

        pnlBonusChallengeLayout.setVerticalGroup(
            pnlBonusChallengeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBonusChallengeLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblBonusChallenge, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBonusDisclaimer)
                .addGap(18, 18, 18)
                .addComponent(txtfBonusName, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(scrlpExplanation, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlBonusChallengeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBonusChallengeLayout.createSequentialGroup()
                        .addComponent(txtfPointsAwarded, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBonusChallengeLayout.createSequentialGroup()
                        .addComponent(lblPointsAwarded, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(pnlBonusChallengeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbtnYesBonus, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblBonusCompleted, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(btnSubmitBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        pnlBonusChallengeLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblBonusCompleted, lblPointsAwarded});

        tabpnMenu.addTab("BONUS CHALLENGE", pnlBonusChallenge);

        pnlBackground.setBackground(new java.awt.Color(204, 255, 153));

        lblBackground.setFont(new java.awt.Font("SimSun", 1, 20)); // NOI18N
        lblBackground.setForeground(new java.awt.Color(51, 102, 0));
        lblBackground.setText("BACKGROUND");

        lblAboutLittleFoot.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        lblAboutLittleFoot.setText("ABOUT LITTLE FOOT");

        lblHowYoureHelping.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        lblHowYoureHelping.setText("HOW YOU'RE MAKING A DIFFERENCE BY COMPETING");

        txtaAbout.setColumns(20);
        txtaAbout.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        txtaAbout.setRows(5);
        sclpnAbout.setViewportView(txtaAbout);

        txtaDifference.setColumns(20);
        txtaDifference.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        txtaDifference.setRows(5);
        scrlpnDifference.setViewportView(txtaDifference);

        lblThankYou.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        lblThankYou.setText("THANK YOU FOR YOUR IMPACT!");

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                .addGap(0, 61, Short.MAX_VALUE)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(scrlpnDifference)
                            .addComponent(lblHowYoureHelping, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                        .addComponent(sclpnAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96))))
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(lblBackground))
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(lblAboutLittleFoot))
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(lblThankYou)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lblAboutLittleFoot, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sclpnAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lblHowYoureHelping, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrlpnDifference, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblThankYou, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabpnMenu.addTab("BACKGROUND", pnlBackground);

        pnlHelp.setBackground(new java.awt.Color(204, 255, 153));

        lblHelp.setFont(new java.awt.Font("SimSun", 1, 20)); // NOI18N
        lblHelp.setForeground(new java.awt.Color(51, 102, 0));
        lblHelp.setText("HELP");

        lblHelpExplanation.setFont(new java.awt.Font("SimSun", 1, 12)); // NOI18N
        lblHelpExplanation.setText("Please Select the Button Related to Your Area of Inquiry");

        btnChallenges.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        btnChallenges.setText("CHALLENGES");

        txtaQueries.setEditable(false);
        txtaQueries.setColumns(20);
        txtaQueries.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        txtaQueries.setRows(5);
        scrlpnHelp.setViewportView(txtaQueries);

        btnUserPass.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        btnUserPass.setText("USERNAME/PASSWORD");

        btnTimeLeft.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        btnTimeLeft.setText("TIME LEFT");

        btnPointSystem.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        btnPointSystem.setText("POINT SYSTEM");

        btnDeclaration.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        btnDeclaration.setText("DECLARATION OF TRUTH");

        btnBonusChallenge.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        btnBonusChallenge.setText("BONUS CHALLENGE");

        btnDailyChecklist.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        btnDailyChecklist.setText("DAILY CHECKLIST");

        btnChallengeTips.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        btnChallengeTips.setText("CHALLENGE TIPS");

        javax.swing.GroupLayout pnlHelpLayout = new javax.swing.GroupLayout(pnlHelp);
        pnlHelp.setLayout(pnlHelpLayout);
        pnlHelpLayout.setHorizontalGroup(
            pnlHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHelpLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblHelpExplanation)
                .addGap(86, 86, 86))
            .addGroup(pnlHelpLayout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(lblHelp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHelpLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(pnlHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrlpnHelp)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlHelpLayout.createSequentialGroup()
                        .addGroup(pnlHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnChallenges, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPointSystem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDailyChecklist, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(btnChallengeTips, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlHelpLayout.createSequentialGroup()
                        .addComponent(btnUserPass, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBonusChallenge, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlHelpLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnTimeLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDeclaration))))
                .addGap(43, 43, 43))
        );

        pnlHelpLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBonusChallenge, btnChallengeTips, btnChallenges, btnDailyChecklist, btnDeclaration, btnPointSystem, btnTimeLeft, btnUserPass});

        pnlHelpLayout.setVerticalGroup(
            pnlHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHelpLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHelpExplanation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUserPass, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBonusChallenge, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChallenges, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeclaration, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTimeLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPointSystem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDailyChecklist, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChallengeTips, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(scrlpnHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pnlHelpLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBonusChallenge, btnChallengeTips, btnChallenges, btnDailyChecklist, btnDeclaration, btnPointSystem, btnTimeLeft, btnUserPass});

        tabpnMenu.addTab("HELP", pnlHelp);

        tabpnChallengeTips.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        tabpnChallengeTips.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N

        pnl1.setBackground(new java.awt.Color(204, 255, 153));

        lblTip1.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        lblTip1.setText("1)");

        txtaTip1.setEditable(false);
        txtaTip1.setColumns(20);
        txtaTip1.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        txtaTip1.setRows(5);
        txtaTip1.setText("TIP:");
        scrpnTip1.setViewportView(txtaTip1);

        btnTip1.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        btnTip1.setText("?");

        javax.swing.GroupLayout pnl1Layout = new javax.swing.GroupLayout(pnl1);
        pnl1.setLayout(pnl1Layout);
        pnl1Layout.setHorizontalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrpnTip1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                    .addComponent(lblTip1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(137, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTip1)
                .addGap(206, 206, 206))
        );
        pnl1Layout.setVerticalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblTip1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scrpnTip1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(btnTip1)
                .addGap(30, 30, 30))
        );

        tabpnChallengeTips.addTab("1", pnl1);

        pnl2.setBackground(new java.awt.Color(204, 255, 153));

        lblTip2.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        lblTip2.setText("2)");

        txtaTip2.setEditable(false);
        txtaTip2.setColumns(20);
        txtaTip2.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        txtaTip2.setRows(5);
        txtaTip2.setText("TIP:");
        scrpnTip2.setViewportView(txtaTip2);

        btnTip2.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        btnTip2.setText("?");

        javax.swing.GroupLayout pnl2Layout = new javax.swing.GroupLayout(pnl2);
        pnl2.setLayout(pnl2Layout);
        pnl2Layout.setHorizontalGroup(
            pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl2Layout.createSequentialGroup()
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl2Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(scrpnTip2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl2Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(lblTip2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(109, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnTip2)
                .addGap(194, 194, 194))
        );
        pnl2Layout.setVerticalGroup(
            pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblTip2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(scrpnTip2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnTip2)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        tabpnChallengeTips.addTab("2", pnl2);

        pnl3.setBackground(new java.awt.Color(204, 255, 153));

        lblTip3.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        lblTip3.setText("3)");

        btnTip3.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        btnTip3.setText("?");

        txtaTip3.setEditable(false);
        txtaTip3.setColumns(20);
        txtaTip3.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        txtaTip3.setRows(5);
        txtaTip3.setText("TIP:");
        scrpnTip7.setViewportView(txtaTip3);

        javax.swing.GroupLayout pnl3Layout = new javax.swing.GroupLayout(pnl3);
        pnl3.setLayout(pnl3Layout);
        pnl3Layout.setHorizontalGroup(
            pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTip3)
                .addGap(204, 204, 204))
            .addGroup(pnl3Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl3Layout.createSequentialGroup()
                        .addComponent(scrpnTip7, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnl3Layout.createSequentialGroup()
                        .addComponent(lblTip3, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                        .addGap(106, 106, 106))))
        );
        pnl3Layout.setVerticalGroup(
            pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblTip3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrpnTip7, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btnTip3)
                .addGap(28, 28, 28))
        );

        tabpnChallengeTips.addTab("3", pnl3);

        pnl4.setBackground(new java.awt.Color(204, 255, 153));

        lblTip4.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        lblTip4.setText("4)");

        txtaTip4.setEditable(false);
        txtaTip4.setColumns(20);
        txtaTip4.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        txtaTip4.setRows(5);
        txtaTip4.setText("TIP:");
        scrpnTip4.setViewportView(txtaTip4);

        btnTip4.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        btnTip4.setText("?");

        javax.swing.GroupLayout pnl4Layout = new javax.swing.GroupLayout(pnl4);
        pnl4.setLayout(pnl4Layout);
        pnl4Layout.setHorizontalGroup(
            pnl4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTip4)
                .addGap(206, 206, 206))
            .addGroup(pnl4Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(pnl4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl4Layout.createSequentialGroup()
                        .addComponent(scrpnTip4, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnl4Layout.createSequentialGroup()
                        .addComponent(lblTip4, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                        .addGap(108, 108, 108))))
        );
        pnl4Layout.setVerticalGroup(
            pnl4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblTip4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrpnTip4, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(btnTip4)
                .addGap(31, 31, 31))
        );

        tabpnChallengeTips.addTab("4", pnl4);

        pnl5.setBackground(new java.awt.Color(204, 255, 153));

        lblTip5.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        lblTip5.setText("5)");

        txtaTip5.setEditable(false);
        txtaTip5.setColumns(20);
        txtaTip5.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        txtaTip5.setRows(5);
        txtaTip5.setText("TIP:");
        scrpnTip5.setViewportView(txtaTip5);

        btnTip5.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        btnTip5.setText("?");

        javax.swing.GroupLayout pnl5Layout = new javax.swing.GroupLayout(pnl5);
        pnl5.setLayout(pnl5Layout);
        pnl5Layout.setHorizontalGroup(
            pnl5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl5Layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(btnTip5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnl5Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(pnl5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrpnTip5)
                    .addComponent(lblTip5, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE))
                .addGap(107, 107, 107))
        );
        pnl5Layout.setVerticalGroup(
            pnl5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl5Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblTip5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrpnTip5, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTip5)
                .addGap(282, 282, 282))
        );

        tabpnChallengeTips.addTab("5", pnl5);

        pnl6.setBackground(new java.awt.Color(204, 255, 153));

        lblTip6.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        lblTip6.setText("6)");

        btnTip6.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        btnTip6.setText("?");

        txtaTip6.setEditable(false);
        txtaTip6.setColumns(20);
        txtaTip6.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        txtaTip6.setRows(5);
        txtaTip6.setText("TIP:");
        scrpnTip11.setViewportView(txtaTip6);

        javax.swing.GroupLayout pnl6Layout = new javax.swing.GroupLayout(pnl6);
        pnl6.setLayout(pnl6Layout);
        pnl6Layout.setHorizontalGroup(
            pnl6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl6Layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(btnTip6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl6Layout.createSequentialGroup()
                .addGroup(pnl6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl6Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(scrpnTip11, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl6Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(lblTip6, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)))
                .addGap(105, 105, 105))
        );
        pnl6Layout.setVerticalGroup(
            pnl6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl6Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblTip6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrpnTip11, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(btnTip6)
                .addGap(36, 36, 36))
        );

        tabpnChallengeTips.addTab("6", pnl6);

        pnl7.setBackground(new java.awt.Color(204, 255, 153));

        lblTip7.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        lblTip7.setText("7)");

        txtaTip7.setEditable(false);
        txtaTip7.setColumns(20);
        txtaTip7.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        txtaTip7.setRows(5);
        txtaTip7.setText("TIP:");
        jScrollPane7.setViewportView(txtaTip7);

        btnTip7.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        btnTip7.setText("?");

        javax.swing.GroupLayout pnl7Layout = new javax.swing.GroupLayout(pnl7);
        pnl7.setLayout(pnl7Layout);
        pnl7Layout.setHorizontalGroup(
            pnl7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl7Layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addGroup(pnl7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl7Layout.createSequentialGroup()
                        .addComponent(lblTip7, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl7Layout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl7Layout.createSequentialGroup()
                        .addComponent(btnTip7)
                        .addGap(215, 215, 215))))
        );
        pnl7Layout.setVerticalGroup(
            pnl7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl7Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblTip7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTip7)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        tabpnChallengeTips.addTab("7", pnl7);

        pnl8.setBackground(new java.awt.Color(204, 255, 153));

        lblTip8.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        lblTip8.setText("8)");

        txtaTip8.setEditable(false);
        txtaTip8.setColumns(20);
        txtaTip8.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        txtaTip8.setRows(5);
        txtaTip8.setText("TIP:");
        scrpnTip8.setViewportView(txtaTip8);

        btnTip8.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        btnTip8.setText("?");

        javax.swing.GroupLayout pnl8Layout = new javax.swing.GroupLayout(pnl8);
        pnl8.setLayout(pnl8Layout);
        pnl8Layout.setHorizontalGroup(
            pnl8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl8Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(btnTip8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl8Layout.createSequentialGroup()
                .addGroup(pnl8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl8Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(scrpnTip8, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl8Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(lblTip8, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)))
                .addGap(109, 109, 109))
        );
        pnl8Layout.setVerticalGroup(
            pnl8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl8Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblTip8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scrpnTip8, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnTip8)
                .addGap(30, 30, 30))
        );

        tabpnChallengeTips.addTab("8", pnl8);

        pnl9.setBackground(new java.awt.Color(204, 255, 153));

        lblTip9.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        lblTip9.setText("9)");

        btnTip9.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        btnTip9.setText("?");

        txtaTip9.setEditable(false);
        txtaTip9.setColumns(20);
        txtaTip9.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        txtaTip9.setRows(5);
        txtaTip9.setText("TIP:");
        jScrollPane8.setViewportView(txtaTip9);

        javax.swing.GroupLayout pnl9Layout = new javax.swing.GroupLayout(pnl9);
        pnl9.setLayout(pnl9Layout);
        pnl9Layout.setHorizontalGroup(
            pnl9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl9Layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(btnTip9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl9Layout.createSequentialGroup()
                .addGroup(pnl9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl9Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl9Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(lblTip9, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)))
                .addGap(103, 103, 103))
        );
        pnl9Layout.setVerticalGroup(
            pnl9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl9Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblTip9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnTip9)
                .addGap(35, 35, 35))
        );

        tabpnChallengeTips.addTab("9", pnl9);

        pnl10.setBackground(new java.awt.Color(204, 255, 153));

        lblTip10.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        lblTip10.setText("10)");

        txtaTip10.setEditable(false);
        txtaTip10.setColumns(20);
        txtaTip10.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        txtaTip10.setRows(5);
        txtaTip10.setText("TIP:");
        scrpnTip10.setViewportView(txtaTip10);

        btnTip10.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        btnTip10.setText("?");

        javax.swing.GroupLayout pnl10Layout = new javax.swing.GroupLayout(pnl10);
        pnl10.setLayout(pnl10Layout);
        pnl10Layout.setHorizontalGroup(
            pnl10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl10Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(lblTip10, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addGap(112, 112, 112))
            .addGroup(pnl10Layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(btnTip10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnl10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl10Layout.createSequentialGroup()
                    .addGap(88, 88, 88)
                    .addComponent(scrpnTip10, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(117, Short.MAX_VALUE)))
        );
        pnl10Layout.setVerticalGroup(
            pnl10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl10Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblTip10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 340, Short.MAX_VALUE)
                .addComponent(btnTip10)
                .addGap(30, 30, 30))
            .addGroup(pnl10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl10Layout.createSequentialGroup()
                    .addGap(89, 89, 89)
                    .addComponent(scrpnTip10, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(139, Short.MAX_VALUE)))
        );

        tabpnChallengeTips.addTab("10", pnl10);

        tabpnMenu.addTab("CHALLENGE TIPS", tabpnChallengeTips);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabpnMenu)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabpnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        tabpnMenu.getAccessibleContext().setAccessibleName("Profile");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
           // java.util.logging.Logger.getLogger(MainMenuScrn.class.getNlblHouseHoldMembersjava.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuScrn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuScrn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuScrn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuScrn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBonusChallenge;
    private javax.swing.JButton btnChallengeTips;
    private javax.swing.JButton btnChallenges;
    private javax.swing.JButton btnDailyChecklist;
    private javax.swing.JButton btnDeclaration;
    private javax.swing.JButton btnPointSystem;
    private java.awt.Button btnSubmitBonus;
    private java.awt.Button btnSubmitChecklist;
    private javax.swing.JButton btnTimeLeft;
    private javax.swing.JButton btnTip1;
    private javax.swing.JButton btnTip10;
    private javax.swing.JButton btnTip2;
    private javax.swing.JButton btnTip3;
    private javax.swing.JButton btnTip4;
    private javax.swing.JButton btnTip5;
    private javax.swing.JButton btnTip6;
    private javax.swing.JButton btnTip7;
    private javax.swing.JButton btnTip8;
    private javax.swing.JButton btnTip9;
    private javax.swing.JButton btnUserPass;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JLabel lblAboutLittleFoot;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblBonusChallenge;
    private javax.swing.JLabel lblBonusCompleted;
    private javax.swing.JLabel lblBonusDisclaimer;
    private javax.swing.JLabel lblChallenge1;
    private javax.swing.JLabel lblChallenge10;
    private javax.swing.JLabel lblChallenge2;
    private javax.swing.JLabel lblChallenge3;
    private javax.swing.JLabel lblChallenge4;
    private javax.swing.JLabel lblChallenge5;
    private javax.swing.JLabel lblChallenge6;
    private javax.swing.JLabel lblChallenge7;
    private javax.swing.JLabel lblChallenge8;
    private javax.swing.JLabel lblChallenge9;
    private javax.swing.JLabel lblChecklistDisclaimer;
    private javax.swing.JLabel lblChecklistSelection;
    private javax.swing.JLabel lblCurrentRanking;
    private javax.swing.JLabel lblDailyChecklist;
    private javax.swing.JLabel lblDay;
    private javax.swing.JLabel lblDaysLeft;
    private javax.swing.JLabel lblHelp;
    private javax.swing.JLabel lblHelpExplanation;
    private javax.swing.JLabel lblHouseHoldMembers;
    private javax.swing.JLabel lblHowYoureHelping;
    private javax.swing.JLabel lblNiceWorkSoFar;
    private javax.swing.JLabel lblPointsAwarded;
    private javax.swing.JLabel lblPointsEarned;
    private javax.swing.JLabel lblProgress;
    private javax.swing.JLabel lblProgressHeading;
    private javax.swing.JLabel lblSelectedChallenges;
    private javax.swing.JLabel lblThankYou;
    private javax.swing.JLabel lblTip1;
    private javax.swing.JLabel lblTip10;
    private javax.swing.JLabel lblTip2;
    private javax.swing.JLabel lblTip3;
    private javax.swing.JLabel lblTip4;
    private javax.swing.JLabel lblTip5;
    private javax.swing.JLabel lblTip6;
    private javax.swing.JLabel lblTip7;
    private javax.swing.JLabel lblTip8;
    private javax.swing.JLabel lblTip9;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblUserProfile;
    private java.awt.List lstSelectedChallenges;
    private javax.swing.JPanel pnl1;
    private javax.swing.JPanel pnl10;
    private javax.swing.JPanel pnl2;
    private javax.swing.JPanel pnl3;
    private javax.swing.JPanel pnl4;
    private javax.swing.JPanel pnl5;
    private javax.swing.JPanel pnl6;
    private javax.swing.JPanel pnl7;
    private javax.swing.JPanel pnl8;
    private javax.swing.JPanel pnl9;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlBonusChallenge;
    private javax.swing.JPanel pnlDailyChecklist;
    private javax.swing.JPanel pnlHelp;
    private javax.swing.JPanel pnlProfile;
    private javax.swing.JPanel pnlProgress;
    private javax.swing.JProgressBar prbar;
    private javax.swing.JProgressBar prbar1;
    private javax.swing.JRadioButton rdbtnYesBonus;
    private javax.swing.JScrollPane sclpnAbout;
    private javax.swing.JScrollPane scrlpExplanation;
    private javax.swing.JScrollPane scrlpnDifference;
    private javax.swing.JScrollPane scrlpnHelp;
    private javax.swing.JScrollPane scrpnTip1;
    private javax.swing.JScrollPane scrpnTip10;
    private javax.swing.JScrollPane scrpnTip11;
    private javax.swing.JScrollPane scrpnTip2;
    private javax.swing.JScrollPane scrpnTip4;
    private javax.swing.JScrollPane scrpnTip5;
    private javax.swing.JScrollPane scrpnTip7;
    private javax.swing.JScrollPane scrpnTip8;
    private javax.swing.JTabbedPane tabpnChallengeTips;
    private javax.swing.JTabbedPane tabpnMenu;
    private java.awt.TextField txtCurrentRanking;
    private java.awt.TextField txtDaysLeft;
    private java.awt.TextField txtHouseholdMembers;
    private java.awt.TextField txtPointsEarned;
    private java.awt.TextField txtUserName;
    private javax.swing.JTextArea txtaAbout;
    private javax.swing.JTextArea txtaChallengeExplanation;
    private javax.swing.JTextArea txtaDifference;
    private javax.swing.JTextArea txtaQueries;
    private javax.swing.JTextArea txtaTip1;
    private javax.swing.JTextArea txtaTip10;
    private javax.swing.JTextArea txtaTip2;
    private javax.swing.JTextArea txtaTip3;
    private javax.swing.JTextArea txtaTip4;
    private javax.swing.JTextArea txtaTip5;
    private javax.swing.JTextArea txtaTip6;
    private javax.swing.JTextArea txtaTip7;
    private javax.swing.JTextArea txtaTip8;
    private javax.swing.JTextArea txtaTip9;
    private javax.swing.JTextField txtfBonusName;
    private javax.swing.JTextField txtfDay;
    private javax.swing.JTextField txtfPointsAwarded;
    // End of variables declaration//GEN-END:variables

}
