/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Taljaard;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author 27649
 */
public class WelcomeScrn extends javax.swing.JFrame {

    /**
     * Creates new form WelcomeScrn
     *
     * @return
     */
    //method generates randomised fact for "fact text area" upon user opening the screen from Facts text file
    public String fact() {
        String fact = "";
        try {
            Scanner scFact = new Scanner(new File("Facts.txt"));
            String[] arrFacts = scFact.nextLine().split("#");
            fact = arrFacts[(int) (Math.random() * ((arrFacts.length - 1) + 1))];

        } catch (FileNotFoundException ex) {
            System.out.println("File not found");;
        }
        return fact;
    }

    public WelcomeScrn() {
        initComponents();
        txtaFact.setText("\t\tDid you know...\n\n" + fact());
    }
    //method for displaying facts in welcome screen 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlWelcome = new javax.swing.JPanel();
        lblWelcome = new java.awt.Label();
        scrlFact = new javax.swing.JScrollPane();
        txtaFact = new javax.swing.JTextArea();
        cmbEntry = new javax.swing.JComboBox<>();
        btnProceed = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlWelcome.setBackground(new java.awt.Color(204, 255, 153));

        lblWelcome.setFont(new java.awt.Font("SimSun", 1, 30)); // NOI18N
        lblWelcome.setText("WELCOME TO LITTLE FOOT!");

        txtaFact.setEditable(false);
        txtaFact.setColumns(20);
        txtaFact.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        txtaFact.setLineWrap(true);
        txtaFact.setRows(5);
        txtaFact.setText("                Did You Know That...");
        scrlFact.setViewportView(txtaFact);

        cmbEntry.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        cmbEntry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LOGIN", "REGISTER NOW" }));

        btnProceed.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        btnProceed.setLabel("PROCEED");
        btnProceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProceedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlWelcomeLayout = new javax.swing.GroupLayout(pnlWelcome);
        pnlWelcome.setLayout(pnlWelcomeLayout);
        pnlWelcomeLayout.setHorizontalGroup(
            pnlWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlWelcomeLayout.createSequentialGroup()
                .addGroup(pnlWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlWelcomeLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlWelcomeLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(scrlFact, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlWelcomeLayout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(cmbEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlWelcomeLayout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(btnProceed, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        pnlWelcomeLayout.setVerticalGroup(
            pnlWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlWelcomeLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(scrlFact, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(cmbEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(btnProceed, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProceedActionPerformed
        // if the choice made in the combo button is to login, the login screen will appear. This is the default choice.
        if (cmbEntry.getSelectedItem().equals("LOGIN")) 
        {
            LoginScrn login = new LoginScrn();
            login.setVisible(true);
            dispose();
        // if the choice made in the combo button is to login, the login screen will appear   
        } else if (cmbEntry.getSelectedItem().equals("REGISTER NOW")){
            RegistrationScrn register = new RegistrationScrn();
            register.setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_btnProceedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {

            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomeScrn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomeScrn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomeScrn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeScrn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomeScrn().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnProceed;
    private javax.swing.JComboBox<String> cmbEntry;
    private java.awt.Label lblWelcome;
    private javax.swing.JPanel pnlWelcome;
    private javax.swing.JScrollPane scrlFact;
    private javax.swing.JTextArea txtaFact;
    // End of variables declaration//GEN-END:variables
}
